name: linefold
description: A Markdown editor for macOS and reading preview app for iOS.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  desktop_drop: ^0.7.1
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  ianvs_design: ^0.4.1
  ianvs_mermaid:
    path: ../packages/ianvs_mermaid
  ianvs_markdown:
    path: ../
  ianvs_markdown_clipboard:
    path: ../packages/ianvs_markdown_clipboard
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  config:
    enable-swift-package-manager: false
  uses-material-design: true
