flowchart TB
N0_0["节点 1·1"] --> N0_1
N0_1["节点 1·2"] --> N0_2
N0_2["节点 1·3"] --> N0_3
N0_3["节点 1·4"] --> N0_4
N0_4["节点 1·5"] --> N0_5
N0_5["节点 1·6"] --> N0_6
N0_6["节点 1·7"] --> N0_7
N0_7["节点 1·8"]
N1_0["节点 2·1"] --> N1_1
N1_1["节点 2·2"] --> N1_2
N1_2["节点 2·3"] --> N1_3
N1_3["节点 2·4"] --> N1_4
N1_4["节点 2·5"] --> N1_5
N1_5["节点 2·6"] --> N1_6
N1_6["节点 2·7"] --> N1_7
N1_7["节点 2·8"]
N2_0["节点 3·1"] --> N2_1
N2_1["节点 3·2"] --> N2_2
N2_2["节点 3·3"] --> N2_3
N2_3["节点 3·4"] --> N2_4
N2_4["节点 3·5"] --> N2_5
N2_5["节点 3·6"] --> N2_6
N2_6["节点 3·7"] --> N2_7
N2_7["节点 3·8"]
N3_0["节点 4·1"] --> N3_1
N3_1["节点 4·2"] --> N3_2
N3_2["节点 4·3"] --> N3_3
N3_3["节点 4·4"] --> N3_4
N3_4["节点 4·5"] --> N3_5
N3_5["节点 4·6"] --> N3_6
N3_6["节点 4·7"] --> N3_7
N3_7["节点 4·8"]
N4_0["节点 5·1"] --> N4_1
N4_1["节点 5·2"] --> N4_2
N4_2["节点 5·3"] --> N4_3
N4_3["节点 5·4"] --> N4_4
N4_4["节点 5·5"] --> N4_5
N4_5["节点 5·6"] --> N4_6
N4_6["节点 5·7"] --> N4_7
N4_7["节点 5·8"]
N5_0["节点 6·1"] --> N5_1
N5_1["节点 6·2"] --> N5_2
N5_2["节点 6·3"] --> N5_3
N5_3["节点 6·4"] --> N5_4
N5_4["节点 6·5"] --> N5_5
N5_5["节点 6·6"] --> N5_6
N5_6["节点 6·7"] --> N5_7
N5_7["节点 6·8"]
N6_0["节点 7·1"] --> N6_1
N6_1["节点 7·2"] --> N6_2
N6_2["节点 7·3"] --> N6_3
N6_3["节点 7·4"] --> N6_4
N6_4["节点 7·5"] --> N6_5
N6_5["节点 7·6"] --> N6_6
N6_6["节点 7·7"] --> N6_7
N6_7["节点 7·8"]
N7_0["节点 8·1"] --> N7_1
N7_1["节点 8·2"] --> N7_2
N7_2["节点 8·3"] --> N7_3
N7_3["节点 8·4"] --> N7_4
N7_4["节点 8·5"] --> N7_5
N7_5["节点 8·6"] --> N7_6
N7_6["节点 8·7"] --> N7_7
N7_7["节点 8·8"]